### ISSUE TITLE
Responses to Updates

### ISSUE THREAD

**Issue by TheThirdOne** [toshima/generalsio#1]
In the event that the generals.io updates, and breaks the websocket protocol (or adds a gameplay mode), how quickly would this repo be updated?

Also, will the api be stable (barring additions/changes accompanying generals.io updates)?

**Comment by toshima** [comment]
Hey,

Thanks for the questions. I'm running a bot using this repo so if it's broken by any game changes, I plan to update the repo asap.

The interface isn't stable yet, especially since the generals.io gameplay and websocket interface don't seem to be stable yet.
